version: "2.2"
services:
  asir_bind9:
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 53:53
    volumes:
      - confdnsubuntu:/etc/bind
  asir_cliente:
    image: ubuntu
    stdin_open: true  
    tty: true         # estas dos líneas equivalen al -it, permiten iniciar una terminal y que se mantenga up el docker
volumes:
  confdnsubuntu:
    external: true    
